import { MongoClient } from 'mongodb'

export const GET = async ()=>{
    try {
        const cities = [
                'Florida, Miami',
                'Florida, Tampa',
                'Florida, Orlando',
                'Florida, St. Petersburg',
                'Florida, Hialeah',
                'Florida, Tallahassee',
                'Florida, Fort Lauderdale',
                'Florida, Port St. Lucie',
                'Florida, Cape Coral',
                'Georgia, Atlanta',
                'Georgia, Augusta',
                'Georgia, Columbus',
                'Georgia, Savannah',
                'Georgia, Athens',
                'Georgia, Sandy Springs',
                'Georgia, Macon',
                'Georgia, Roswell',
                'Georgia, Albany',
                'Georgia, Johns Creek',
                'Hawaii, Honolulu',
                'Hawaii, Hilo',
                'Hawaii, Kailua',
                'Hawaii, Kapolei',
                'Hawaii, Kaneohe',
                'Hawaii, Waipahu',
                'Hawaii, Pearl City',
                'Hawaii, Mililani Town',
                'Hawaii, Kahului',
                'Hawaii, Kihei',
                'Idaho, Boise',
                'Idaho, Meridian',
                'Idaho, Nampa',
                'Idaho, Idaho Falls',
                'Idaho, Pocatello',
                'Idaho, Caldwell',
                'Idaho, Coeur d\'Alene',
                'Idaho, Twin Falls',
                'Idaho, Lewiston',
                'Idaho, Post Falls',
                'Illinois, Chicago',
                'Illinois, Aurora',
                'Illinois, Rockford',
                'Illinois, Joliet',
                'Illinois, Naperville',
                'Illinois, Springfield',
                'Illinois, Peoria',
                'Illinois, Elgin',
                'Illinois, Waukegan',
                'Illinois, Cicero',
                'Indiana, Indianapolis',
                'Indiana, Fort Wayne',
                'Indiana, Evansville',
                'Indiana, South Bend',
                'Indiana, Carmel',
                'Indiana, Fishers',
                'Indiana, Bloomington',
                'Indiana, Hammond',
                'Indiana, Gary',
                'Indiana, Lafayette',
                'Iowa, Des Moines',
                'Iowa, Cedar Rapids',
                'Iowa, Davenport',
                'Iowa, Sioux City',
                'Iowa, Iowa City',
                'Iowa, Waterloo',
                'Iowa, Council Bluffs',
                'Iowa, Ames',
                'Iowa, Dubuque',
                'Iowa, West Des Moines',
                'Kansas, Wichita',
                'Kansas, Overland Park',
                'Kansas, Kansas City',
                'Kansas, Olathe',
                'Kansas, Topeka',
                'Kansas, Lawrence',
                'Kansas, Shawnee',
                'Kansas, Manhattan',
                'Kansas, Lenexa',
                'Kansas, Salina',
                'Kentucky, Louisville',
                'Kentucky, Lexington',
                'Kentucky, Bowling Green',
                'Kentucky, Owensboro',
                'Kentucky, Covington',
                'Kentucky, Hopkinsville',
                'Kentucky, Frankfort',
                'Kentucky, Henderson',
                'Kentucky, Richmond',
                'Kentucky, Florence',
                'Louisiana, New Orleans',
                'Louisiana, Baton Rouge',
                'Louisiana, Shreveport',
                'Louisiana, Lafayette',
                'Louisiana, Lake Charles',
                'Louisiana, Kenner',
                'Louisiana, Bossier City',
                'Louisiana, Monroe',
                'Louisiana, Alexandria',
                'Louisiana, New Iberia',
                'Maine, Portland',
                'Maine, Lewiston',
                'Maine, Bangor',
                'Maine, South Portland',
                'Maine, Auburn',
                'Maine, Biddeford',
                'Maine, Sanford',
                'Maine, Augusta',
                'Maine, Scarborough',
                'Maine, Saco',
                'Maryland, Baltimore',
                'Maryland, Columbia',
                'Maryland, Germantown',
                'Maryland, Silver Spring',
                'Maryland, Frederick',
                'Maryland, Rockville',
                'Maryland, Gaithersburg',
                'Maryland, Bowie',
                'Maryland, Hagerstown',
                'Maryland, Annapolis',
                'Massachusetts, Boston',
                'Massachusetts, Worcester',
                'Massachusetts, Springfield',
                'Massachusetts, Lowell',
                'Massachusetts, Cambridge',
                'Massachusetts, New Bedford',
                'Massachusetts, Brockton',
                'Massachusetts, Quincy',
                'Massachusetts, Lynn',
                'Massachusetts, Fall River',
                'Michigan, Detroit',
                'Michigan, Grand Rapids',
                'Michigan, Warren',
                'Michigan, Sterling Heights',
                'Michigan, Lansing',
                'Michigan, Ann Arbor',
                'Michigan, Flint',
                'Michigan, Dearborn',
                'Michigan, Livonia',
                'Michigan, Troy',
                'Minnesota, Minneapolis',
                'Minnesota, Saint Paul',
                'Minnesota, Rochester',
                'Minnesota, Duluth',
                'Minnesota, Bloomington',
                'Minnesota, Brooklyn Park',
                'Minnesota, Plymouth',
                'Minnesota, Saint Cloud',
                'Minnesota, Woodbury',
                'Minnesota, Eagan',
                'Mississippi, Jackson',
                'Mississippi, Gulfport',
                'Mississippi, Southaven',
                'Mississippi, Hattiesburg',
                'Mississippi, Biloxi',
                'Mississippi, Meridian',
                'Mississippi, Tupelo',
                'Mississippi, Olive Branch',
                'Mississippi, Greenville',
                'Mississippi, Horn Lake',
                'Missouri, Kansas City',
                'Missouri, Saint Louis',
                'Missouri, Springfield',
                'Missouri, Independence',
                'Missouri, Columbia',
                'Missouri, Lee\'s Summit',
                'Missouri, O\'Fallon',
                'Missouri, Saint Joseph',
                'Missouri, Saint Charles',
                'Missouri, Saint Peters',
                'Montana, Billings',
                'Montana, Missoula',
                'Montana, Great Falls',
                'Montana, Bozeman',
                'Montana, Butte',
                'Montana, Helena',
                'Montana, Kalispell',
                'Montana, Havre',
                'Montana, Anaconda',
                'Montana, Miles City',
                'Nebraska, Omaha',
                'Nebraska, Lincoln',
                'Nebraska, Bellevue',
                'Nebraska, Grand Island',
                'Nebraska, Kearney',
                'Nebraska, Fremont',
                'Nebraska, Hastings',
                'Nebraska, North Platte',
                'Nebraska, Norfolk',
                'Nebraska, Columbus',
                'Nevada, Las Vegas',
                'Nevada, Henderson',
                'Nevada, Reno',
                'Nevada, North Las Vegas',
                'Nevada, Sparks',
                'Nevada, Carson City',
                'Nevada, Elko',
                'Nevada, Boulder City',
                'Nevada, Mesquite',
                'Nevada, Fernley',
                'New Hampshire, Manchester',
                'New Hampshire, Nashua',
                'New Hampshire, Concord',
                'New Hampshire, Derry',
                'New Hampshire, Dover',
                'New Hampshire, Rochester',
                'New Hampshire, Salem',
                'New Hampshire, Merrimack',
                'New Hampshire, Hudson',
                'New Hampshire, Londonderry',
                'New Jersey, Newark',
                'New Jersey, Jersey City',
                'New Jersey, Paterson',
                'New Jersey, Elizabeth',
                'New Jersey, Edison',
                'New Jersey, Woodbridge',
                'New Jersey, Lakewood',
                'New Jersey, Toms River',
                'New Jersey, Hamilton',
                'New Jersey, Clifton',
                'New Mexico, Albuquerque',
                'New Mexico, Las Cruces',
                'New Mexico, Rio Rancho',
                'New Mexico, Santa Fe',
                'New Mexico, Roswell',
                'New Mexico, Farmington',
                'New Mexico, Clovis',
                'New Mexico, Hobbs',
                'New Mexico, Alamogordo',
                'New Mexico, Carlsbad',
                'New York, New York City' 
        ];
    
        const uri = 'mongodb+srv://petrusheya:jEaik9RPhjNUaENA@cluster0.jsot3qd.mongodb.net/pendora?retryWrites=true&w=majority&appName=Cluster0'
        const client = new MongoClient(uri);
        console.log('Client initilized')
        
        await client.connect()
        const db = client.db("pendora"); // Specify the database name
        const collection = db.collection('locations'); // Specify the collection name
        console.log('db specs set')
      
        // Insert the array as a document
      
        const result = await collection.insertOne({ cities });
        console.log(`Document inserted with _id: ${result.insertedId}`);
      
        client.close();
        console.log('thats all folks')
        
        return Response.json({res: 'done'}, {status: 200})
        
    } catch (error) {
        console.log('Error Occured:', error)
        return Response.json({status:500})
    }
}